language: php

php:
  - 5.3
  - 5.4

services: 
  - mongodb
  - memcached
  - redis-server  

before_script:
  - php -r '$m = new MongoClient();echo "Mongo driver version: ".$m::VERSION."\n";'
  - php --info
  - composer install --dev
  - phpenv config-add tests/travis/php.ini
  - mysql -e 'create database poc_tests;'
  - vendor/bin/phploc  src/

script: 
  - vendor/bin/phpunit --verbose
