language: php

php:
  - 5.3
  - 5.4

services: 
  - mongodb
  - memcached
  - redis-server  

before_script:
  - composer install --dev
  - phpenv config-add tests/travis/php.ini
  - mysql -e 'create database poc_tests;'

script: 
  - vendor/bin/phpunit --verbose --coverage-text
