language: php

php:
  - 5.3
  
before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev
  - mysql -e 'create database poc_tests;'
script: vendor/bin/phpunit