<?php
namespace Poc\PocEvents;

interface PocEventNames {
  const BEFORE_OUTPUT_SENT_TO_CLIENT_AFTER_OUTPUT_STORED = 'Poc_BEFORE_OUTPUT_SENT_TO_CLIENT_AFTER_OUTPUT_STORED';
  const BEFORE_STORE_OUTPUT = 'Poc_BEFORE_STORE_OUTPUT';
  const BEFORE_OUTPUT_SENT_TO_CLIENT_NO_CACHING_PROCESS_INVLOVED = 'Poc_BEFORE_OUTPUT_SENT_TO_CLIENT_NO_CACHING_PROCESS_INVLOVED';
  const BEFORE_OUTPUT_SENT_TO_CLIENT_FETCHED_FROM_CACHE = 'Poc_BEFORE_OUTPUT_SENT_TO_CLIENT_FETCHED_FROM_CACHE';
  const CONSTRUCTOR_BEGINING = 'Poc_CONSTRUCTOR_BEGINING';
  const CONSTRUCTOR_END = 'Poc_CONSTRUCTOR_END';
  const FUNCTION_START_BEGINNING = 'Poc_FUNCTION_START_BEGINNING';
  const FUNCTION_START_END = 'Poc_FUNCTION_START_END';
  const DIES = 'Poc_DIE';
  
  //const BEFORE_OUTPUT_SENT_TO_CLIENT = 'bcostc';
}

