<?php
namespace Poc\PocEvents;

interface PocEventNames
{

    const OUTPUT_STORED = 'OUTPUT_STORED';

    const BEFORE_OUTPUT_SENT_TO_CLIENT_AFTER_OUTPUT_STORED = 'BEFORE_OUTPUT_SENT_TO_CLIENT_AFTER_OUTPUT_STORED';

    const BEFORE_STORE_OUTPUT = 'BEFORE_STORE_OUTPUT';

    const BEFORE_OUTPUT_SENT_TO_CLIENT_NO_CACHING_PROCESS_INVLOVED = 'BEFORE_OUTPUT_SENT_TO_CLIENT_NO_CACHING_PROCESS_INVLOVED';

    const BEFORE_OUTPUT_SENT_TO_CLIENT_FETCHED_FROM_CACHE = 'BEFORE_OUTPUT_SENT_TO_CLIENT_FETCHED_FROM_CACHE';

    const CONSTRUCTOR_BEGINING = 'CONSTRUCTOR_BEGINING';

    const CONSTRUCTOR_END = 'CONSTRUCTOR_END';

    const FUNCTION_START_BEGINNING = 'FUNCTION_START_BEGINNING';

    const FUNCTION_START_ENDS_CACHE_STARTS = 'FUNCTION_START_END_CACHE_STARTS';

    const FUNCTION_START_END = 'FUNCTION_START_END';

    const FUNCTION_FETCHCACHE_BEGINING = 'FUNCTION_FETCHCACHE_BEGINING';

    const DIES = 'DIE';

    const BEFORE_THE_DECISION_IF_WE_CAN_STORE_THE_GENERATED_CONTENT = 'BEFORE_THE_DECISION_IF_WE_CAN_STORE_THE_GENERATED_CONTENT';

    // const BEFORE_OUTPUT_SENT_TO_CLIENT = 'bcostc';
}

